version: '3.1'

services:

  db-service:
    container_name: db-service
    build:
      context: db
    restart: always
    env_file:
      - db/.env
    ports:
      - "5000:5432"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 250M
        reservations:
          memory: 250M

  #############################

  node-js:
    container_name: node-js
    build:
      context: .
    depends_on:
      - db-service
    ports:
      - "4000:8080"
    restart: always
